services:
  job-connect:
    container_name: job-connect-backend
    build:
      context: .
      dockerfile: Dockerfile
    image: fastapi
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - job-connect
    volumes:
      - ".:/usr/src/app"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    user: "1000:1000"

networks:
  job-connect:
    driver: bridge

